name: pruebas ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  verificar_codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Mostrar archivos (Opcional, para depurar)
        run: ls -R